spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasktrackr
    username: tasktrackr
    password: tasktrackr
  jpa:
    hibernate:
       ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: testetestandolabcrescer@gmail.com
    password: kpgovlkhyqhvahgn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  error:
    include-message: always
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
