DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS task CASCADE;

CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    telefone VARCHAR(14) NOT NULL,
    senha VARCHAR(100) NOT NULL,
    ativo BOOLEAN NOT NULL,
	points INTEGER default(0),
    foto VARCHAR(255)
);
ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE(email);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_telefone UNIQUE(telefone);

CREATE TABLE task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(100) NOT NULL,
    description TEXT,
    created_at TIMESTAMP NOT NULL,
    deadline_date TIMESTAMP NOT NULL,
    priority VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    user_id BIGINT NOT NULL,
    finish_date TIMESTAMP
);
ALTER TABLE task ADD CONSTRAINT pk_task PRIMARY KEY (id);
ALTER TABLE task ADD CONSTRAINT fk_task_user FOREIGN KEY (user_id) REFERENCES Usuario (id);
ALTER TABLE task ADD CONSTRAINT ck_task_priority CHECK(priority in('LOW', 'AVERAGE', 'HIGH'));
ALTER TABLE task ADD CONSTRAINT ck_task_status CHECK(status in('IN_PROGRESS', 'COMPLETED'));